name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - rails_version: rails-6.0
            ruby_version: "3.1"
          - rails_version: rails-6.1
            ruby_version: "3.1"
          - rails_version: rails-7.0
            ruby_version: "3.1"
          - rails_version: rails-7.1
            ruby_version: "3.1"
          - rails_version: rails-7.2
            ruby_version: "3.1"
          - rails_version: rails-8.0
            ruby_version: "3.2"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        bundle install
        bundle exec appraisal install
    
    - name: Run tests
      run: |
        bundle exec appraisal ${{ matrix.rails_version }} rspec
    
    - name: Run linter
      run: |
        bundle exec standardrb --format simple

