name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - rails_version: rails-6.0
            ruby_version: "3.1"
          - rails_version: rails-6.1
            ruby_version: "3.1"
          - rails_version: rails-7.0
            ruby_version: "3.1"
          - rails_version: rails-7.1
            ruby_version: "3.1"
          - rails_version: rails-7.2
            ruby_version: "3.1"
          - rails_version: rails-8.0
            ruby_version: "3.2"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: false
    
    - name: Install appraisal gem
      run: gem install appraisal --no-document
    
    - name: Generate appraisal gemfile
      run: appraisal install ${{ matrix.rails_version }} || true
    
    - name: Set BUNDLE_GEMFILE
      run: echo "BUNDLE_GEMFILE=gemfiles/${{ matrix.rails_version }}/Gemfile" >> $GITHUB_ENV
    
    - name: Install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
        gemfile: gemfiles/${{ matrix.rails_version }}/Gemfile
    
    - name: Run tests
      run: bundle exec appraisal ${{ matrix.rails_version }} rspec
    
    - name: Run linter
      if: matrix.ruby_version == '3.2'
      env:
        BUNDLE_GEMFILE: Gemfile
      run: |
        bundle install
        bundle exec standardrb --format simple

