name: test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: rails6
            ruby_version: "3.1"
          - gemfile: rails72
            ruby_version: "3.2"
          - gemfile: rails8ruby34
            ruby_version: "3.4"
          - gemfile: rails8ruby4
            ruby_version: "4.0"
          - gemfile: rails8truffleruby
            ruby_version: "truffleruby"
    
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    
    - name: Run tests
      run: bundle exec polyrun parallel-rspec --workers 5 --merge-failures

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - run: POLYRUN_COVERAGE=1 bundle exec polyrun parallel-rspec --workers 5 --merge-failures
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        continue-on-error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        if: ${{ !cancelled() }}
        continue-on-error: true
        with:
          report_type: test_results
          files: coverage/junit-coverage.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
